#!/bin/bash

### BEGIN INIT INFO
# Provides:          dtopd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start dtop daemon at boot time
# Description:       Enable dtop service provided by daemon.
### END INIT INFO

# Must be a valid filename
DAEMON=dtop
NAME=dtopd
PIDFILE=/var/run/$NAME.pid
#This is the command to be run, give the full pathname
DAEMON_ROOT=/usr/local/share/dtop
DAEMON=/usr/bin/dtop
DAEMON_OPTS="-c /etc/dtop/default.json"

case "$1" in
start)
	printf "%-50s" "Starting $NAME..."
	cd $DAEMON_ROOT
	PID=`$DAEMON $DAEMON_OPTS > /dev/null 2>&1 & echo $!`
	#echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_ROOT
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
  	$0 stop
  	$0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac