# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos-6.5"
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130731.box"
  config.vm.synced_folder "../../", "/dtop-dist"

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
  
    vb.customize ["modifyvm", :id, "--memory", "512"]

    config.vm.provision "puppet" do |puppet|
      puppet.options = "--verbose --debug"
    end
  end
end