#!/bin/sh
 
### BEGIN INIT INFO
# Provides:          dtopd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start dtop daemon at boot time
# Description:       Enable dtop service provided by daemon.
### END INIT INFO

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
 
# Must be a valid filename
NAME=dtopd
PIDFILE=/var/run/$NAME.pid
#This is the command to be run, give the full pathname
DAEMON_ROOT=/usr/local/share/dtop
DAEMON=/usr/bin/dtop
DAEMON_OPTS="-c /etc/dtop/default.json"
SS="start-stop-daemon"

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
 
case "$1" in
  start)
    echo -n "Starting daemon: "$NAME"\n"
	$SS --start --background -d $DAEMON_ROOT --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
	;;
  stop)
    echo -n "Stopping daemon: "$NAME"\n"
	$SS --stop --quiet --oknodo --pidfile $PIDFILE
	rm $PIDFILE
	;;
  status)
    echo -n "Status of daemon $NAME: "
	$SS --status --pidfile $PIDFILE
	EC=$?
	test 0 -eq $EC && echo "running"
	test 0 -ne $EC && echo "not running"
	exit $EC
	;;
  restart)
    echo -n "Restarting daemon: "$NAME"\n"
	$SS --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
	$SS --start --background -d $DAEMON_ROOT --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
	;;
  *)
	echo "Usage: "$1" {start|stop|status|restart}"
	exit 1
esac
 
exit 0
