#!/bin/bash
# This helper script is called by the Makefile for the different distributions.
export GOROOT=$1
export GOPATH=$2
export GOOS=$3
export GOARCH=$4
export OUTPUT=$5
cd ${GOROOT}/src/
source make.bash
cd -
${GOROOT}/bin/go build -o ${OUTPUT} eu.dominiek/dtop