#!/bin/sh
 
### BEGIN INIT INFO
# Provides:          dtopd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start dtop daemon at boot time
# Description:       Enable dtop service provided by daemon.
### END INIT INFO

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e
 
# Must be a valid filename
NAME=dtopd
PIDFILE=/var/run/$NAME.pid
#This is the command to be run, give the full pathname
DAEMON_ROOT=/opt/dtop
DAEMON=/opt/dtop/dtop
DAEMON_OPTS="--port 12345"
 
export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
 
case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
	start-stop-daemon --start --background -d $DAEMON_ROOT --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        echo "."
	;;
  stop)
        echo -n "Stopping daemon: "$NAME
	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
        echo "."
	;;
  restart)
        echo -n "Restarting daemon: "$NAME
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
	echo "."
	;;
 
  *)
	echo "Usage: "$1" {start|stop|restart}"
	exit 1
esac
 
exit 0